# Run whenever there's a commit
trigger:
  branches:
    include:
    - '*'

jobs:
- job: run_tests
  displayName: Run Tests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - script: npm ci
    displayName: 'npm ci'

  - script: npm run compile
    displayName: 'npm run compile'

  - script: npm test
    displayName: 'npm test'
    env:
      DISPLAY: ':99.0'
